name: Push to Organization Repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git for pushing to Org repo
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push to Organization Repo
        env:
          ORG_PAT: ${{ secrets.ORG_PAT }}
        run: |
          git remote add org-origin https://x-access-token:${{ secrets.ORG_PAT }}@github.com/geidai-amc-lab/pcb-making-ws-2024.git
          git push org-origin main
