name: Sync to Organization Repo

on:
  push:
    branches:
      - main  # 監視するブランチを指定

jobs:
  sync_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Push to Organization Repo
        run: |
          git remote add org-origin git@github.com:geidai-amc-lab/pcb-making-ws-2024.git
          git push org-origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
